### ISSUE TITLE
Not connecting to muse 2

### ISSUE THREAD

**Issue by kylemath** [CaydenPierce/MuServe#4]
Installed android studio
cloned repo
changed SDK to previous version .8 after error
build successful
changed pixel 3 phone to usb dev mode
plugged into computer
accepted usb dev mode
build successful, app opens, connecting, turn on muse
doesn't find any devices:

pixel 3
macbook pro newest os
muse 2

**Comment by kylemath** [comment]
![image](https://user-images.githubusercontent.com/3662613/75105479-f2020a80-55d0-11ea-880c-a5b0b3c68750.png)

**Comment by CaydenPierce** [comment]
This is due to not granting permissions... must manually go into settings and grant permissions.
